import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>VNV Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vnv.png" />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>
        <section>
          <h2>Our Solutions</h2>
        </section>
      </main>
    </>
  );
}
